name: publish
on: [push]
jobs:
  publish-grampie-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Grampie Docker image
        run: |
          docker build . --tag ghcr.io/sodoto/grampie:latest
          docker run ghcr.io/sodoto/grampie:latest
          docker push ghcr.io/sodoto/grampie:latest